### ISSUE TITLE
Selecting an issue to work on fails when master branch does not exist

### ISSUE THREAD

**Issue by philip-brink** [GitLiveApp/GitLive#28]
After selecting an issue to work on from the popup, gitlive fails to switch to the new task when the principal branch is not called master.

In my case, the principle branch is called `main`. I get the following error:

```
Couldn't checkout master
invalid reference: master
```

![image](https://user-images.githubusercontent.com/6272888/106546840-100f0500-64da-11eb-8d3c-19de77405a4d.png)

OS: Linux
IDE: Jetbrains rider
VCS: gitlab.com

**Comment by Reedyuk** [comment]
Hi @philip-brink - many thanks to raising the issue, could you tell me what version of the plugin are you using? As i believe the latest plugin 10.0.5 has it fixed.

**Comment by nbransby** [comment]
Hi @philip-brink thanks for reporting this, I believe this should be fixed now, could you (after restarting your ide) try again and let us know?

**Comment by philip-brink** [comment]
@nbransby Thanks for checking into this!

I tried again, but it still fails with the same error message. The version I'm using is 10.0.5, I tried restarting and checking for updates, but there were no changes.

**Comment by nbransby** [comment]
Thanks @philip-brink I believe it should work now after a restart (doesn't need an update)

**Comment by philip-brink** [comment]
Great! Works perfectly!
